# -*- coding: utf-8 -*-
"""cattely_dataset

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YoBJx_P28c5jq8Dlp9eRPcYJXKtNpiVH
"""

from google.colab import drive
drive.mount('/content/drive')

import os
print(os.listdir("/content/drive/MyDrive"))

import os
from PIL import Image
import torch
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as T
import torchvision.models as models
import torch.nn as nn


class CattelyDataset(Dataset):
    def __init__(self, root_dir, image_size=224):
        self.samples = []

        self.classes = sorted([
            d for d in os.listdir(root_dir)
            if os.path.isdir(os.path.join(root_dir, d))
        ])

        self.class_to_idx = {cls: i for i, cls in enumerate(self.classes)}

        for cls in self.classes:
            cls_path = os.path.join(root_dir, cls)

            for img_name in os.listdir(cls_path):
                if img_name.lower().endswith((".jpg", ".jpeg", ".png")):
                    self.samples.append(
                        (os.path.join(cls_path, img_name),
                         self.class_to_idx[cls])
                    )

        self.transform = T.Compose([
            T.Resize((image_size, image_size)),
            T.RandomRotation(8),
            T.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.15),
            T.GaussianBlur(kernel_size=3),
            T.ToTensor(),
            T.Normalize(mean=[0.5]*3, std=[0.5]*3)
        ])

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        img = Image.open(img_path).convert("RGB")
        img = self.transform(img)
        return img, label

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

data_path = "/content/drive/MyDrive/Cattely-Cattle-Face-Images-Dataset-main"

dataset = CattelyDataset(data_path)
loader = DataLoader(dataset, batch_size=32, shuffle=True)

num_classes = len(dataset.class_to_idx)

print("Number of classes:", num_classes)
print("Number of images:", len(dataset))

model = models.resnet18(weights="IMAGENET1K_V1")
model.fc = nn.Linear(model.fc.in_features, num_classes)
model = model.to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=0.0003)
criterion = nn.CrossEntropyLoss()

for epoch in range(5):
    model.train()
    total_loss = 0
    correct = 0
    total = 0

    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    accuracy = 100 * correct / total
    print(f"Epoch {epoch+1}, Loss: {total_loss/len(loader):.4f}, Accuracy: {accuracy:.2f}%")